modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="maris_decoration"
version="${version}"
displayName="Maris' Decoration"
authors="MarryDream"
description='''Contains some decorative blocks I need'''
[[dependencies.maris_decoration]]
modId="forge"
mandatory=true
versionRange="[47.4.10,48)"
ordering="NONE"
side="BOTH"
[[dependencies.maris_decoration]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
[[dependencies.maris_decoration]]
modId="create"
mandatory=true
versionRange="[6.0.8,6.1)"
ordering="AFTER"
side="BOTH"
[[dependencies.maris_decoration]]
modId="copycats"
mandatory=false
versionRange="[3.0.10,3.1)"
ordering="AFTER"
side="BOTH"
