modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="maris_decoration"
version="${version}"
displayName="Maris' Decoration"
authors="MarryDream"
description='''Contains some decorative blocks I need'''
[[dependencies.maris_decoration]]
modId="neoforge"
type="required"
versionRange="[21.1.252,21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.maris_decoration]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
[[dependencies.maris_decoration]]
modId="create"
type="required"
versionRange="[6.0.10,6.1)"
ordering="AFTER"
side="BOTH"
[[dependencies.maris_decoration]]
modId="copycats"
type="optional"
versionRange="[3.0.9,3.1)"
ordering="AFTER"
side="BOTH"
